"""initial user scoped schema

Revision ID: 966685d63c93
Revises: 
Create Date: 2026-08-03 17:16:56.969777
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '966685d63c93'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=True),
    sa.Column('extension_kind', sa.String(length=80), nullable=True),
    sa.Column('extension_schema_version', sa.Integer(), nullable=True),
    sa.Column('extension_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(extension_kind IS NULL AND extension_schema_version IS NULL AND extension_payload = '{}'::jsonb) OR (extension_kind IS NOT NULL AND char_length(extension_kind) > 0 AND extension_schema_version IS NOT NULL)", name='ck_agent_run_event_extension_complete'),
    sa.CheckConstraint('extension_schema_version IS NULL OR extension_schema_version >= 1', name='ck_agent_run_event_extension_schema_version'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_events_user_run_created', 'agent_run_events', ['run_id', 'created_at'], unique=False)
    op.create_index('ix_agent_run_events_user_run_seq', 'agent_run_events', ['run_id', 'seq'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('input_message', sa.String(length=4000), nullable=False),
    sa.Column('result_message', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_user_created', 'agent_runs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_user_thread_created', 'agent_runs', ['user_id', 'thread_id', 'created_at'], unique=False)
    op.create_index('uq_agent_runs_active_thread', 'agent_runs', ['user_id', 'thread_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running') AND deleted_at IS NULL"))
    op.create_table('calendar_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('timing_kind', sa.String(length=16), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('reminder', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('created_operation_key', sa.String(length=64), nullable=True),
    sa.Column('updated_by_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_operation_key', sa.String(length=64), nullable=True),
    sa.Column('cancelled_by_run_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_operation_key', sa.String(length=64), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(timing_kind = 'timed' AND scheduled_date IS NULL AND start_time IS NOT NULL) OR (timing_kind = 'anytime' AND scheduled_date IS NOT NULL AND start_time IS NULL AND end_time IS NULL AND reminder IS NULL)", name='ck_calendar_entries_timing_shape'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calendar_entries_user_cancelled_by_run', 'calendar_entries', ['user_id', 'cancelled_by_run_id'], unique=False)
    op.create_index('ix_calendar_entries_user_created_by_run', 'calendar_entries', ['user_id', 'created_by_run_id'], unique=False)
    op.create_index('ix_calendar_entries_user_date', 'calendar_entries', ['user_id', 'scheduled_date'], unique=False)
    op.create_index('ix_calendar_entries_user_start', 'calendar_entries', ['user_id', 'start_time'], unique=False)
    op.create_index('uq_calendar_entries_user_run_cancel_operation', 'calendar_entries', ['user_id', 'cancelled_by_run_id', 'cancelled_operation_key'], unique=True, postgresql_where=sa.text('cancelled_by_run_id IS NOT NULL AND cancelled_operation_key IS NOT NULL'))
    op.create_index('uq_calendar_entries_user_run_create_operation', 'calendar_entries', ['user_id', 'created_by_run_id', 'created_operation_key'], unique=True, postgresql_where=sa.text('created_by_run_id IS NOT NULL AND created_operation_key IS NOT NULL'))
    op.create_index('uq_calendar_entries_user_run_update_operation', 'calendar_entries', ['user_id', 'updated_by_run_id', 'updated_operation_key'], unique=True, postgresql_where=sa.text('updated_by_run_id IS NOT NULL AND updated_operation_key IS NOT NULL'))
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.String(length=4000), nullable=False),
    sa.Column('presentation_kind', sa.String(length=80), nullable=True),
    sa.Column('presentation_schema_version', sa.Integer(), nullable=True),
    sa.Column('presentation_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(presentation_kind IS NULL AND presentation_schema_version IS NULL AND presentation_payload = '{}'::jsonb) OR (presentation_kind IS NOT NULL AND presentation_schema_version IS NOT NULL)", name='ck_conversation_message_presentation_complete'),
    sa.CheckConstraint("presentation_kind IS NULL OR role = 'assistant'", name='ck_conversation_message_presentation_assistant_only'),
    sa.CheckConstraint('presentation_schema_version IS NULL OR presentation_schema_version >= 1', name='ck_conversation_message_presentation_schema_version'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_conversation_messages_user_run_role', 'conversation_messages', ['user_id', 'run_id', 'role'], unique=True)
    op.create_table('conversation_states',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=80), nullable=True),
    sa.Column('interaction_schema_version', sa.Integer(), nullable=True),
    sa.Column('interaction_source_run_id', sa.UUID(), nullable=True),
    sa.Column('interaction_prompt', sa.String(length=1000), nullable=True),
    sa.Column('interaction_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(interaction_type IS NULL AND interaction_schema_version IS NULL AND interaction_source_run_id IS NULL AND interaction_prompt IS NULL AND interaction_payload = '{}'::jsonb AND expires_at IS NULL) OR (interaction_type IS NOT NULL AND interaction_schema_version IS NOT NULL AND interaction_source_run_id IS NOT NULL AND interaction_prompt IS NOT NULL AND expires_at IS NOT NULL)", name='ck_conversation_state_interaction_complete'),
    sa.CheckConstraint('interaction_schema_version IS NULL OR interaction_schema_version >= 1', name='ck_conversation_state_interaction_schema_version'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('conversation_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=8000), nullable=True),
    sa.Column('summary_through_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_conversation_thread_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_threads_user_updated', 'conversation_threads', ['user_id', 'updated_at'], unique=False)
    op.create_index('uq_conversation_threads_primary_user', 'conversation_threads', ['user_id'], unique=True, postgresql_where=sa.text('is_primary IS TRUE AND deleted_at IS NULL'))
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idempotency_keys_user_run', 'idempotency_keys', ['run_id'], unique=False)
    op.create_index('uq_idempotency_keys_user_key', 'idempotency_keys', ['user_id', 'key'], unique=True)
    op.create_table('provider_usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=240), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_usage_user_created', 'provider_usage_records', ['user_id', 'created_at'], unique=False)
    op.create_index('uq_provider_usage_user_run', 'provider_usage_records', ['user_id', 'run_id'], unique=True)
    op.create_table('reminder_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=240), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_deliveries_due', 'reminder_deliveries', ['status', 'next_attempt_at', 'scheduled_for'], unique=False)
    op.create_index('ix_reminder_deliveries_user_created', 'reminder_deliveries', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_reminder_deliveries_user_unread', 'reminder_deliveries', ['user_id', 'read_at'], unique=False, postgresql_where=sa.text("status = 'delivered' AND deleted_at IS NULL"))
    op.create_index('uq_reminder_deliveries_active_source_channel', 'reminder_deliveries', ['user_id', 'source_type', 'source_id', 'channel'], unique=True, postgresql_where=sa.text("status IN ('pending', 'processing') AND deleted_at IS NULL"))
    op.create_table('task_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('row_version', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('reminder', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_run_id', sa.UUID(), nullable=True),
    sa.Column('created_operation_key', sa.String(length=64), nullable=True),
    sa.Column('updated_by_run_id', sa.UUID(), nullable=True),
    sa.Column('updated_operation_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_items_user_status_due', 'task_items', ['user_id', 'status', 'due_at'], unique=False)
    op.create_index('uq_task_items_user_run_create_operation', 'task_items', ['user_id', 'created_by_run_id', 'created_operation_key'], unique=True, postgresql_where=sa.text('created_by_run_id IS NOT NULL AND created_operation_key IS NOT NULL'))
    op.create_index('uq_task_items_user_run_update_operation', 'task_items', ['user_id', 'updated_by_run_id', 'updated_operation_key'], unique=True, postgresql_where=sa.text('updated_by_run_id IS NOT NULL AND updated_operation_key IS NOT NULL'))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('voice_transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=240), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('audio_size_bytes', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=12000), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=240), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_transcripts_user_created', 'voice_transcripts', ['user_id', 'created_at'], unique=False)
    op.create_table('external_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issuer', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject', name='uq_external_identity_subject')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_tokens_token_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index('uq_password_reset_tokens_active_user', 'password_reset_tokens', ['user_id'], unique=True, postgresql_where=sa.text('used_at IS NULL'))
    op.create_table('user_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_token_hash', 'user_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_token_hash', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_profiles')
    op.drop_table('user_credentials')
    op.drop_index('uq_password_reset_tokens_active_user', table_name='password_reset_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_index('ix_password_reset_tokens_token_hash', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('external_identities')
    op.drop_index('ix_voice_transcripts_user_created', table_name='voice_transcripts')
    op.drop_table('voice_transcripts')
    op.drop_table('users')
    op.drop_index('uq_task_items_user_run_update_operation', table_name='task_items', postgresql_where=sa.text('updated_by_run_id IS NOT NULL AND updated_operation_key IS NOT NULL'))
    op.drop_index('uq_task_items_user_run_create_operation', table_name='task_items', postgresql_where=sa.text('created_by_run_id IS NOT NULL AND created_operation_key IS NOT NULL'))
    op.drop_index('ix_task_items_user_status_due', table_name='task_items')
    op.drop_table('task_items')
    op.drop_index('uq_reminder_deliveries_active_source_channel', table_name='reminder_deliveries', postgresql_where=sa.text("status IN ('pending', 'processing') AND deleted_at IS NULL"))
    op.drop_index('ix_reminder_deliveries_user_unread', table_name='reminder_deliveries', postgresql_where=sa.text("status = 'delivered' AND deleted_at IS NULL"))
    op.drop_index('ix_reminder_deliveries_user_created', table_name='reminder_deliveries')
    op.drop_index('ix_reminder_deliveries_due', table_name='reminder_deliveries')
    op.drop_table('reminder_deliveries')
    op.drop_index('uq_provider_usage_user_run', table_name='provider_usage_records')
    op.drop_index('ix_provider_usage_user_created', table_name='provider_usage_records')
    op.drop_table('provider_usage_records')
    op.drop_index('uq_idempotency_keys_user_key', table_name='idempotency_keys')
    op.drop_index('ix_idempotency_keys_user_run', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('uq_conversation_threads_primary_user', table_name='conversation_threads', postgresql_where=sa.text('is_primary IS TRUE AND deleted_at IS NULL'))
    op.drop_index('ix_conversation_threads_user_updated', table_name='conversation_threads')
    op.drop_table('conversation_threads')
    op.drop_table('conversation_states')
    op.drop_index('uq_conversation_messages_user_run_role', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('uq_calendar_entries_user_run_update_operation', table_name='calendar_entries', postgresql_where=sa.text('updated_by_run_id IS NOT NULL AND updated_operation_key IS NOT NULL'))
    op.drop_index('uq_calendar_entries_user_run_create_operation', table_name='calendar_entries', postgresql_where=sa.text('created_by_run_id IS NOT NULL AND created_operation_key IS NOT NULL'))
    op.drop_index('uq_calendar_entries_user_run_cancel_operation', table_name='calendar_entries', postgresql_where=sa.text('cancelled_by_run_id IS NOT NULL AND cancelled_operation_key IS NOT NULL'))
    op.drop_index('ix_calendar_entries_user_start', table_name='calendar_entries')
    op.drop_index('ix_calendar_entries_user_date', table_name='calendar_entries')
    op.drop_index('ix_calendar_entries_user_created_by_run', table_name='calendar_entries')
    op.drop_index('ix_calendar_entries_user_cancelled_by_run', table_name='calendar_entries')
    op.drop_table('calendar_entries')
    op.drop_index('uq_agent_runs_active_thread', table_name='agent_runs', postgresql_where=sa.text("status IN ('queued', 'running') AND deleted_at IS NULL"))
    op.drop_index('ix_agent_runs_user_thread_created', table_name='agent_runs')
    op.drop_index('ix_agent_runs_user_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_agent_run_events_user_run_seq', table_name='agent_run_events')
    op.drop_index('ix_agent_run_events_user_run_created', table_name='agent_run_events')
    op.drop_table('agent_run_events')
    # ### end Alembic commands ###
